import { JSX } from 'react';

import { Geist, Geist_Mono } from 'next/font/google';
import Image from 'next/image';

import type { Metadata } from 'next';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div style={{ position: 'fixed', inset: 0, zIndex: -1, pointerEvents: 'none' }}>
          <Image
            className="main-bg"
            src="/images/main-bg.avif"
            alt=""
            fill
            style={{ objectFit: 'cover' }}
            priority
          />
        </div>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
